### ISSUE TITLE
Failure to compile with GHC 7.6, 7.8

### ISSUE THREAD

**Issue by ivanperez-keera** [byorgey/MonadRandom#51]
Hi.

The current version of MonadRandom assumes that `Applicative` is (implicitly) imported from the `Prelude`. See:

https://app.travis-ci.com/github/ivanperez-keera/dunai/jobs/591375353
https://app.travis-ci.com/github/ivanperez-keera/dunai/jobs/591375354

```
Failed to build MonadRandom-0.6.
Build log (
/home/travis/.cabal/logs/ghc-7.8.4/MonadRandom-0.6-28a9dc439132888a18de46add6a85267329e63834f4df8f4b6ba84966f75dca8.log
):
Configuring library for MonadRandom-0.6..
Preprocessing library for MonadRandom-0.6..
Building library for MonadRandom-0.6..
[1 of 7] Compiling Control.Monad.Random.Class ( Control/Monad/Random/Class.hs, dist/build/Control/Monad/Random/Class.o )
[2 of 7] Compiling Control.Monad.Trans.Random.Strict ( Control/Monad/Trans/Random/Strict.hs, dist/build/Control/Monad/Trans/Random/Strict.o )

Control/Monad/Trans/Random/Strict.hs:157:22:
    Not in scope: type constructor or class ‘Applicative’

cabal: Failed to build MonadRandom-0.6 (which is required by
taggingmonad-0.1.0.1, dunai-test-0.9.1 and others). See the build log above
for details.
```

A conditional import might help for the case of applicative, as in:
```haskell
#if !MIN_VERSION_base(4,8,0)                                                    
import Control.Applicative (Applicative)
#endif 
```

There may be other modules and functions that also need to be imported explictly for some versions of GHC/base.

Related: https://github.com/ivanperez-keera/dunai/issues/337

**Comment by byorgey** [comment]
Thanks for the report.  However, [as noted in the changelog](https://hackage.haskell.org/package/MonadRandom-0.6/changelog), with the `MonadRandom-0.6` release I explicitly dropped support for GHC 7.6 and 7.8.  Those are very old and I'm not really interested in inserting CPP just to support them.

**Comment by ivanperez-keera** [comment]
Thanks for the answer. Noted.

**Comment by ivanperez-keera** [comment]
Wait. If that's the case, shouldn't MonadRandom specify that it requires base 4.8 or higher?

**Comment by ivanperez-keera** [comment]
And, if so, it might make sense to publish a revision to the cabal file, as opposed to a MonadRandom 0.6.1 that addresses this, so that cabal doesn't attempt to install MonadRandom 0.6 with old versions of GHC.

**Comment by byorgey** [comment]
Very good point, thanks!  `MonadRandom-0.6` has now been revised on Hackage to require `bsae >= 4.8`.

**Comment by ivanperez-keera** [comment]
Great! Thanks!
